<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260501190020 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE loan_calculations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, monto DOUBLE PRECISION NOT NULL, tasa_anual DOUBLE PRECISION NOT NULL, plazo_meses INT NOT NULL, pago_extra DOUBLE PRECISION NOT NULL, frecuencia VARCHAR(20) NOT NULL, pago_mensual DOUBLE PRECISION NOT NULL, interes_total DOUBLE PRECISION NOT NULL, total_pagado DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE85D88A76ED395 ON loan_calculations (user_id)');
        $this->addSql('ALTER TABLE loan_calculations ADD CONSTRAINT FK_3AE85D88A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE loan_calculations DROP CONSTRAINT FK_3AE85D88A76ED395');
        $this->addSql('DROP TABLE loan_calculations');
    }
}
