<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260212211703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chat_conversations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5813432EA76ED395 ON chat_conversations (user_id)');
        $this->addSql('CREATE TABLE chat_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, role VARCHAR(20) NOT NULL, metadata JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, conversation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF20C9A69AC0396 ON chat_messages (conversation_id)');
        $this->addSql('ALTER TABLE chat_conversations ADD CONSTRAINT FK_5813432EA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chat_messages ADD CONSTRAINT FK_EF20C9A69AC0396 FOREIGN KEY (conversation_id) REFERENCES chat_conversations (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transactions ALTER synchronized DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chat_conversations DROP CONSTRAINT FK_5813432EA76ED395');
        $this->addSql('ALTER TABLE chat_messages DROP CONSTRAINT FK_EF20C9A69AC0396');
        $this->addSql('DROP TABLE chat_conversations');
        $this->addSql('DROP TABLE chat_messages');
        $this->addSql('ALTER TABLE transactions ALTER synchronized SET DEFAULT \'pending\'');
    }
}
