<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260114155424 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE budget_categories (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount DOUBLE PRECISION NOT NULL, budget_id INT NOT NULL, category_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECF4892836ABA6B8 ON budget_categories (budget_id)');
        $this->addSql('CREATE INDEX IDX_ECF4892812469DE2 ON budget_categories (category_id)');
        $this->addSql('CREATE TABLE budgets (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DCAA9548A76ED395 ON budgets (user_id)');
        $this->addSql('ALTER TABLE budget_categories ADD CONSTRAINT FK_ECF4892836ABA6B8 FOREIGN KEY (budget_id) REFERENCES budgets (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE budget_categories ADD CONSTRAINT FK_ECF4892812469DE2 FOREIGN KEY (category_id) REFERENCES categories (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE budgets ADD CONSTRAINT FK_DCAA9548A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE budget_categories DROP CONSTRAINT FK_ECF4892836ABA6B8');
        $this->addSql('ALTER TABLE budget_categories DROP CONSTRAINT FK_ECF4892812469DE2');
        $this->addSql('ALTER TABLE budgets DROP CONSTRAINT FK_DCAA9548A76ED395');
        $this->addSql('DROP TABLE budget_categories');
        $this->addSql('DROP TABLE budgets');
    }
}
