<?php

namespace App\DataFixtures;

use App\Entity\Budget;
use App\Entity\BudgetCategory;
use App\Entity\Category;
use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

/**
 * Creates one monthly budget for each of the last 5 months plus the current month,
 * covering the same date window generated by TransactionFixtures.
 * Each budget assigns a spending limit to every expense category so that the
 * budget health panel and digest features have data to display from the start.
 *
 * Depends on CategoryFixtures and requires the dev user to exist in the database.
 */
class BudgetFixtures extends Fixture implements DependentFixtureInterface
{
    private const USER_EMAIL = 'alejandrogoa@gmail.com';

    /**
     * Monthly spending limits per expense category in COP.
     * Values are intentionally set slightly below average spending so the
     * budget health panel shows a realistic mix of over- and under-budget categories.
     */
    private const CATEGORY_LIMITS = [
        'Alimentos' => 800000,
        'Transporte' => 400000,
        'Entretenimiento' => 300000,
        'Salud' => 250000,
        'Educación' => 200000,
        'Otros' => 150000,
    ];

    /**
     * Creates one Budget per month covering the last 5 months through the current month.
     * Each budget contains a BudgetCategory entry for every expense category defined
     * in CATEGORY_LIMITS. Skips any category that does not exist in the database.
     *
     * Throws RuntimeException if the dev user is not found.
     */
    public function load(ObjectManager $manager): void
    {
        $user = $manager->getRepository(User::class)->findOneBy(['email' => self::USER_EMAIL]);

        if (!$user) {
            throw new \RuntimeException('Usuario "' . self::USER_EMAIL . '" no encontrado. Haz login con Google primero y luego ejecuta los fixtures.');
        }

        // Build a name-indexed map of expense categories for fast lookup.
        $categories = $manager->getRepository(Category::class)->findBy(['type' => 'gasto']);
        $categoryMap = [];
        foreach ($categories as $cat) {
            $categoryMap[$cat->getName()] = $cat;
        }

        // Generate one budget per month: 5 months back up to the current month.
        $now = new \DateTime();
        for ($monthsBack = 5; $monthsBack >= 0; --$monthsBack) {
            $ref = (clone $now)->modify("-{$monthsBack} months");
            $startDate = new \DateTime($ref->format('Y-m-01'));
            $endDate = new \DateTime($ref->format('Y-m-t'));

            $budget = new Budget();
            $budget->setUser($user);
            $budget->setStartDate($startDate);
            $budget->setEndDate($endDate);

            foreach (self::CATEGORY_LIMITS as $categoryName => $limit) {
                if (!isset($categoryMap[$categoryName])) {
                    continue;
                }

                $budgetCategory = new BudgetCategory();
                $budgetCategory->setCategory($categoryMap[$categoryName]);
                $budgetCategory->setAmount((float) $limit);
                $budget->addBudgetCategory($budgetCategory);
            }

            $manager->persist($budget);
        }

        $manager->flush();
    }

    /** Returns the fixture classes that must be loaded before this one. */
    public function getDependencies(): array
    {
        return [CategoryFixtures::class];
    }
}
